<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <!-- Wemogy.Core -->
    <PackageVersion Include="Microsoft.ApplicationInsights" Version="3.1.2" />
    <PackageVersion Include="prometheus-net" Version="8.2.1" />
    <PackageVersion Include="CaseExtensions" Version="1.1.0" />
    <PackageVersion Include="Castle.Core.AsyncInterceptor" Version="2.1.0" />
    <PackageVersion Include="FastExpressionCompiler" Version="5.4.1" />
    <PackageVersion Include="FluentValidation" Version="12.1.1" />
    <PackageVersion Include="JWT" Version="11.1.0" />
    <PackageVersion Include="Macross.Json.Extensions" Version="3.0.0" />
    <PackageVersion Include="Mapster" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="Polly" Version="8.7.0" />
    <PackageVersion Include="Polly.Contrib.WaitAndRetry" Version="1.1.1" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.9" />
    <PackageVersion Include="Refit.HttpClientFactory" Version="13.1.0" />
    <PackageVersion Include="System.IO.Abstractions" Version="22.1.1" />
    <PackageVersion Include="YamlDotNet" Version="18.1.0" />
    <PackageVersion Include="NuGetizer" Version="1.4.9" />

    <!-- Wemogy.Core.Tests -->
    <PackageVersion Include="Bogus" Version="35.6.5" />
    <PackageVersion Include="Divergic.Logging.Xunit" Version="4.3.1" />
    <PackageVersion Include="FluentAssertions" Version="8.10.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageVersion Include="NSubstitute" Version="5.3.0" />
    <PackageVersion Include="WireMock.Net" Version="2.12.0" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="coverlet.msbuild" Version="10.0.1" />

    <!-- Shared -->
    <PackageVersion Include="Wemogy.StyleCop" Version="0.2.2" />
  </ItemGroup>
</Project>
