name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build-lib:
    name: Build Library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build .NET
        uses: ./.github/actions/dotnet
        with:
          wemogy-packages-token: ${{ secrets.WEMOGY_PACKAGES_TOKEN }}
          version: ${{ steps.release-version.outputs.next-version }}${{ github.event.inputs.version && 'pre' || '' }}

  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: yarn install
        working-directory: docs
      - run: yarn build
        working-directory: docs
